# Generated by Django 2.0.5 on 2018-05-29 19:30

import InscripcionPostgrado.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InscripcionPostgrado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='Cod_asignatura',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='[A-Z]{2}[0-9]{4}')]),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='Nombre_asig',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='coordinacion',
            name='Cod_coordinacion',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='[A-Z]{2}')]),
        ),
        migrations.AlterField(
            model_name='coordinacion',
            name='Nombre_coordinacion',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='credito',
            name='Nro_Tarjeta',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='[0-9]{18}')]),
        ),
        migrations.AlterField(
            model_name='debito',
            name='Nro_Cuenta',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='[0-9]{20}')]),
        ),
        migrations.AlterField(
            model_name='debito',
            name='Nro_Tarjeta',
            field=models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(regex='[0-9]{18}')]),
        ),
        migrations.AlterField(
            model_name='debito',
            name='Tipo',
            field=models.CharField(max_length=9, validators=[InscripcionPostgrado.models.tipo_debito_restr]),
        ),
        migrations.AlterField(
            model_name='decanato',
            name='Nombre_decanato',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='deposito',
            name='Referencia',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='[0-9]{20}')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Apellidos',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Carnet',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='[0-9]{2}\\-[0-9]{5}')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Nombres',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='Apellidos',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='Id_prof',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='[0-9]')]),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='Nombres',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='se_ofrece',
            name='Horario',
            field=models.CharField(max_length=5, validators=[InscripcionPostgrado.models.hora_se_ofrece_restr]),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='Nro_Referencia',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(regex='[0-9]{20}')]),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='Anio',
            field=models.IntegerField(validators=[InscripcionPostgrado.models.anio_trimestre_restr]),
        ),
        migrations.AlterField(
            model_name='trimestre',
            name='Periodo',
            field=models.CharField(max_length=20, validators=[InscripcionPostgrado.models.periodo_trimestre_restr]),
        ),
    ]
